mtlynch/ketohub_web_app

.travis.yml

There are no unit tests to run yet.

Removing Coveralls from build

---

app/app.js
app/index.html

Adding hardcoded dummy data to the Angular scope for temporary testing.
Implementing an ng-repeat to display recipes and links.

Adding basic layout with dummy data

---

app/index.html

To prevent the flicker before the page compiles.
This fixes #18.

Adding ng-cloak

---

app/index.html
bower.json

Switching from bower to a CDN for bower and Angular sources.
Fixes #8.

Switching to CDN for Angular, Bootstrap

---

app/app.js
app/index.html

Changing CSS for recipe boxes.
Shortening URL to just root domain.

Improving UX on mobile

---

app/app.js
app/index.html

Switching to firebaseArray for pulling down recipes from database.

Switching to firebaseArray

---

app/index.html

Adding a footer with contact email

---

app/index.html

Adding Google Analytics

---

app/index.html
package.json

Adding autotrack.js library

---

.travis.yml
app/app.css
build
package.json

Fixing CSS style and adding formatter to build

---

.bowerrc
.gitignore
.jscsrc
.jshintignore
bower.json
package.json

Removing bower

---

app/app.js
app/index.html
app/views/pagination.html
app/views/recipeList.html
karma.conf.js
package.json

Switching to angular-bootstrap pagination

---

app/app.js
app/app_test.js
app/views/recipeList.html

Adding detail in the recipe card about how long ago the recipe was published.

Adding publish time

---

src/app/app.module.ts
src/app/highlighted-result.pipe.spec.ts
src/app/highlighted-result.pipe.ts
src/app/recipe-list/recipe-list.component.html
src/app/recipe-list/recipe-list.component.ts
src/styles.css

Also displays matching ingredients.

Add highlighting for search results

---

src/app/_pipes/highlighted-result/highlighted-result.pipe.spec.ts
src/app/_pipes/highlighted-result/highlighted-result.pipe.ts

Fixing error on multiple keyword highlight

---

src/app/recipe-list/recipe-list.component.html
src/app/recipe-list/recipe-list.component.ts

Instead of having each part of the HTML call filteredRecipes, this change
switches the design so that we calculate the filtered recipes any time the
filters change and store it in the recipes variable.

Pre-computing recipe filter

---

src/app/recipe-list/recipe-list.component.html

Hide search results when user erases query

---

src/app/_pipes/highlighted-result/highlighted-result.pipe.spec.ts
src/app/_pipes/highlighted-result/highlighted-result.pipe.ts

Now overlapping search terms don't screw up highlighting.
Fixes #92

Fixing search highlighting

---

src/app/_components/recipe-list/recipe-list.component.css
src/app/_components/recipe-list/recipe-list.component.html
src/app/constants.ts

Changing recipe display to card format

---

package-lock.json
package.json
src/app/_components/recipe-list/recipe-list.component.html
src/app/app.module.ts

ngx-bootstrap's pagination wasn't resetting when we changed the page number
in the model.

Switch to ng-bootstrap

---

src/app/_components/mailing-list/mailing-list.component.html

Was missing ngNoForm so angular was trying to override submit behavior.

Fixing mailing list

---

package-lock.json
src/app/_components/nav/nav.component.css
src/app/_components/nav/nav.component.html

Fixes bug where links were not showing in nav

Fixes bug where links were not showing in nav

---

.travis.yml
package.json

Changing to just use the local copy instead of requiring it to be installed
globally on the dev system.

Fixing scssfmt binary

---

Dockerfile

We only need it on the deploy system

Skipping function install within Docker container

---

package.json
src/app/_components/recipe-card/recipe-card.component.spec.ts
src/app/_components/recipe-list/recipe-list.component.spec.ts
src/app/_components/recipe-list/recipe-list.component.ts
src/tsconfig.spec.json

instantiation unit tests

---

src/app/_components/recipe-list/recipe-list.component.spec.ts
src/app/_components/recipe-list/recipe-list.component.ts
src/app/app.module.ts

Migrate to HttpClientModule

---

Dockerfile
e2e/app.e2e-spec.ts
e2e/app.po.ts
protractor.conf.js

add some e2e tests

---

src/app/_components/nav/nav.component.scss
src/app/_components/recipe-card/recipe-card.component.ts
src/app/_components/recipe-list/recipe-list.component.html
src/app/_components/recipe-list/recipe-list.component.scss
src/app/_components/recipe-list/recipe-list.component.ts

Hiding meal filters behind a collapsing button.
Moving the recipe count to above the search box so that it updates visibly
on mobile.

Rearranging top elements to look better on mobile

---

src/app/_services/recipe-data.service.spec.ts

tests for RecipeDataService

---

package-lock.json
package.json

Removing chromium dev dependency
